[theme]
base = "light"
backgroundColor = "#FAF4EB"
secondaryBackgroundColor = "#F0E5D0"
textColor = "#2D1F0F"
primaryColor = "#337AB7"
font = "sans serif"

[server]
headless = true
port = 8501

[client]
showErrorDetails = false
